server:
  port: 80

spring:
  application:
    name: orb-gateway-api
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8088/oauth2/jwks # orb-auth-server의 JWKS 엔드포인트로 직접호출
      blacklist-uri: http://localhost:8088/oauth2/blacklist # orb-auth-server의 블랙리스트 엔드포인트로 직접호출

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka # Eureka 서버 URL
  instance:
    hostname: localhost

logging:
  level:
    root: INFO
    org:
      springframework:
        cloud:
          gateway: INFO
  logback:
    rollingpolicy:
      clean-history-on-start: false
  pattern:
    console: "%clr([%d{yyyy-MM-dd HH:mm:ss.SSS}]){blue}%clr([${HOSTNAME}])[%thread][%X{uuid}][%p][%c]%clr([%M:%L]) - %msg %nopex%n%ex{full}"